# Generated by Django 5.1.7 on 2026-07-28 08:43

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutAndQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('story', models.TextField(blank=True)),
                ('email_id', models.EmailField(blank=True, max_length=254)),
                ('front_image', models.ImageField(null=True, upload_to='images/pics')),
                ('grid_big', models.ImageField(null=True, upload_to='images/pics')),
                ('grid_small_one', models.ImageField(null=True, upload_to='images/pics')),
                ('grid_small_two', models.ImageField(null=True, upload_to='images/pics')),
                ('parrallex_img', models.ImageField(null=True, upload_to='images/pics')),
                ('facebook', models.URLField(null=True)),
                ('instagram', models.URLField(null=True)),
                ('tiktok', models.URLField(null=True)),
                ('youtube', models.URLField(null=True)),
                ('tag', models.CharField(blank=True, help_text='Add a comma after each tag and make sure it is less than 5.', max_length=100, null=True)),
                ('year_of_experiences', models.IntegerField(blank=True, null=True)),
                ('class_completed', models.IntegerField(blank=True, null=True)),
                ('client_taught', models.IntegerField(blank=True, null=True)),
                ('instagram_follower', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('content', ckeditor.fields.RichTextField()),
                ('thumbnail', models.ImageField(upload_to='images/thumbnails')),
                ('date', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoreValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('emoji', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='CustomService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(blank=True, default=0, null=True)),
                ('weight', models.IntegerField(blank=True, default=0, null=True)),
                ('gender', models.TextField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')])),
                ('activity_level', models.TextField(blank=True, choices=[('Sedentary', 'Sedentary (little or no exercise)'), ('Lightly Active', 'Lightly Active (light exercise/sports 1-3 days/week)'), ('Moderately Active', 'Moderately Active (moderate exercise/sports 3-5 days/week)'), ('Very Active', 'Very Active (hard exercise/sports 6-7 days a week)'), ('Super Active', 'Super Active (very hard exercise/sports & physical job or 2x training)')])),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('goal_choices', models.CharField(blank=True, choices=[('Fat Loss & Toning', 'Fat Loss & Toning'), ('Building Muscle & Strength', 'Building Muscle & Strength'), ('General Health & Mobility', 'General Health & Mobility'), ('Rehabilitation', 'Rehabilitation'), ('HYROX / Event Prep', 'HYROX / Event Prep'), ('Other', 'Other')], max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('special_notes', models.TextField(blank=True)),
                ('equipment_used', models.TextField(blank=True)),
                ('preferred_duration', models.CharField(blank=True, choices=[('1 Week Plan', '1 Week Plan'), ('4 Weeks Plan', '4 Weeks Plan'), ('12 Weeks Plan', '12 Weeks Plan')], max_length=20)),
                ('workout_time', models.CharField(blank=True, choices=[('30 minutes', '30 minutes'), ('45 minutes', '45 minutes'), ('1 hour', '1 hour')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('info', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('icon', models.ImageField(upload_to='images/pics')),
                ('slug', models.SlugField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceFeatureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_item', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonial', models.CharField(max_length=150)),
                ('user_name', models.CharField(max_length=80)),
                ('user_category', models.CharField(default='A member', max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_sessions', models.IntegerField(default=1)),
                ('age', models.IntegerField()),
                ('gender', models.TextField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')])),
                ('started_training_from', models.DateField()),
                ('any_problem', models.CharField(default='N/A', max_length=500)),
                ('status', models.CharField(choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed')], default='Ongoing', max_length=100)),
                ('paid_or_not', models.CharField(blank=True, choices=[('Paid', 'Paid'), ('Not Paid', 'Not Paid'), ('Half Paid', 'Half Paid')], max_length=100, null=True)),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.service')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.BigIntegerField(blank=True, default=0, null=True)),
                ('message', models.TextField(blank=True)),
                ('preferred_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.service')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='feature',
            field=models.ManyToManyField(blank=True, related_name='services', to='website.servicefeatureitem'),
        ),
    ]
