# Generated by Django 4.1.4 on 2022-12-31 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('detail', models.CharField(max_length=80)),
                ('price', models.IntegerField()),
                ('icon', models.ImageField(upload_to='images/pics')),
            ],
        ),
    ]
