# Generated by Django 4.1.4 on 2023-01-01 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_post_date_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
