# Generated by Django 4.1.4 on 2023-01-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_aboutandquote_backgroundimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutandquote',
            name='facebook',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='aboutandquote',
            name='instagram',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='aboutandquote',
            name='pinterest',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='aboutandquote',
            name='youtube',
            field=models.URLField(null=True),
        ),
    ]
