# Generated by Django 4.1.1 on 2023-01-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_aboutandquote_facebook_aboutandquote_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutandquote',
            name='logo',
            field=models.ImageField(null=True, upload_to='images/logo'),
        ),
    ]
