# Generated by Django 4.1.1 on 2023-01-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_aboutandquote_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutandquote',
            name='logo',
            field=models.FileField(null=True, upload_to='images/icon'),
        ),
    ]
