# Generated by Django 4.1.4 on 2023-05-18 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_aboutandquote_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonial', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=80)),
                ('user_img', models.ImageField(upload_to='images/testimonial')),
            ],
        ),
    ]
