# Generated by Django 5.1.7 on 2026-05-04 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='testimonial',
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.TextField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')])),
                ('started_training_from', models.DateField()),
                ('any_problem', models.TextField()),
                ('status', models.TextField(choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed')])),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.service')),
            ],
        ),
    ]
