# Generated by Django 5.1.7 on 2026-05-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_alter_testimonial_testimonial_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
