# Generated by Django 5.1.7 on 2026-05-14 13:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_alter_service_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='detail',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
