# Generated by Django 5.1.7 on 2026-05-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_alter_service_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
