# Generated by Django 5.1.7 on 2026-05-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_service_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceFeatureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_item', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='service',
            name='detail',
        ),
        migrations.AddField(
            model_name='service',
            name='service',
            field=models.ManyToManyField(blank=True, related_name='services', to='website.servicefeatureitem'),
        ),
    ]
