# Generated by Django 5.1.7 on 2026-05-19 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_servicefeatureitem_remove_service_detail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='service',
            new_name='feature',
        ),
    ]
