# Generated by Django 5.1.7 on 2026-05-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_rename_service_service_feature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='user_img',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='user_category',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='client',
            name='any_problem',
            field=models.TextField(default='N/A'),
        ),
    ]
