# Generated by Django 5.1.7 on 2026-05-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_remove_testimonial_user_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutandquote',
            name='email_id',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='aboutandquote',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
