# Generated by Django 5.1.7 on 2026-05-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_aboutandquote_email_id_aboutandquote_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='user_category',
            field=models.CharField(default='A member', max_length=80),
        ),
    ]
