# Generated by Django 5.1.7 on 2026-05-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutandquote',
            name='quoteContainerImage',
            field=models.ImageField(null=True, upload_to='images/bg'),
        ),
    ]
