# Generated by Django 5.1.7 on 2026-05-22 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_aboutandquote_quotecontainerimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
