# Generated by Django 5.1.7 on 2026-06-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField(max_length=10)),
                ('goal_choices', models.CharField(blank=True, choices=[('Fat Loss & Toning', 'Fat Loss & Toning'), ('Building Muscle & Strength', 'Building Muscle & Strength'), ('General Health & Mobility', 'General Health & Mobility'), ('Rehabilitation', 'Rehabilitation'), ('HYROX / Event Prep', 'HYROX / Event Prep'), ('Other', 'Other')], max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('special_notes', models.TextField(blank=True)),
                ('equipment_used', models.TextField(blank=True)),
                ('preffered_duration', models.CharField(blank=True, choices=[('45 minutes', '45 minutes'), ('1 hour', '1 hour'), ('30 minutes', '30 minutes')], max_length=20)),
            ],
        ),
    ]
