# Generated by Django 5.1.7 on 2026-06-03 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_customservice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customservice',
            old_name='preffered_duration',
            new_name='preferred_duration',
        ),
    ]
