# Generated by Django 5.1.7 on 2026-06-03 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_rename_preffered_duration_customservice_preferred_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='customservice',
            name='workout_time',
            field=models.CharField(blank=True, choices=[('45 minutes', '45 minutes'), ('1 hour', '1 hour'), ('30 minutes', '30 minutes')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customservice',
            name='preferred_duration',
            field=models.CharField(blank=True, choices=[('1 Week Plan', '1 Week Plan'), ('4 Weeks Plan', '4 Weeks Plan'), ('12 Weeks Plan', '12 Weeks Plan')], max_length=20),
        ),
    ]
