# Generated by Django 5.1.7 on 2026-06-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_customservice_workout_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customservice',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customservice',
            name='gender',
            field=models.TextField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')]),
        ),
        migrations.AddField(
            model_name='customservice',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
