# Generated by Django 5.1.7 on 2026-06-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_customservice_age_customservice_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customservice',
            name='activity_level',
            field=models.TextField(blank=True, choices=[('Sedentary', 'Sedentary (little or no exercise)'), ('Lightly Active', 'Lightly Active (light exercise/sports 1-3 days/week)'), ('Moderately Active', 'Moderately Active (moderate exercise/sports 3-5 days/week)'), ('Very Active', 'Very Active (hard exercise/sports 6-7 days a week)'), ('Super Active', 'Super Active (very hard exercise/sports & physical job or 2x training)')]),
        ),
    ]
