# Generated by Django 5.1.7 on 2026-06-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_customservice_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customservice',
            name='tag',
        ),
        migrations.AddField(
            model_name='aboutandquote',
            name='tag',
            field=models.CharField(blank=True, help_text='Add a comma after each tag and make sure it is less than 5.', max_length=100, null=True),
        ),
    ]
