# Generated by Django 5.1.7 on 2026-06-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_remove_customservice_tag_aboutandquote_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='total_sessions',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed')], max_length=100),
        ),
    ]
