# Generated by Django 5.1.7 on 2026-06-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0034_client_total_sessions_alter_client_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='paid_or_not',
            field=models.CharField(blank=True, choices=[('Paid', 'Paid'), ('Not Paid', 'Not Paid')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aboutandquote',
            name='phone_number',
            field=models.IntegerField(default=9812312312),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customservice',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
