# Generated by Django 5.1.7 on 2026-06-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0035_client_paid_or_not_alter_aboutandquote_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='phone_number',
            field=models.IntegerField(max_length=10),
        ),
    ]
