# Generated by Django 5.1.7 on 2026-06-28 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0036_alter_booking_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed')], default='Ongoing', max_length=100),
        ),
    ]
