# Generated by Django 5.1.7 on 2026-06-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0037_alter_client_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='any_problem',
            field=models.CharField(default='N/A', max_length=500),
        ),
    ]
