# Generated by Django 5.1.7 on 2026-07-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0038_alter_client_any_problem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='paid_or_not',
            field=models.CharField(blank=True, choices=[('Paid', 'Paid'), ('Not Paid', 'Not Paid'), ('Half Paid', 'Half Paid')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customservice',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customservice',
            name='workout_time',
            field=models.CharField(blank=True, choices=[('30 minutes', '30 minutes'), ('45 minutes', '45 minutes'), ('1 hour', '1 hour')], max_length=20),
        ),
    ]
