# Generated by Django 5.1.7 on 2026-07-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0039_alter_booking_phone_number_alter_client_paid_or_not_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutandquote',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
