# Generated by Django 5.1.7 on 2026-07-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0041_remove_aboutandquote_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutandquote',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
