# Generated by Django 5.1.7 on 2026-07-21 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0042_aboutandquote_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutandquote',
            name='phone_number',
        ),
    ]
