# Generated by Django 5.1.7 on 2026-07-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0043_remove_aboutandquote_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('emoji', models.CharField(max_length=2)),
            ],
        ),
        migrations.RenameField(
            model_name='aboutandquote',
            old_name='pinterest',
            new_name='tiktok',
        ),
        migrations.RemoveField(
            model_name='aboutandquote',
            name='backgroundImage',
        ),
        migrations.RemoveField(
            model_name='aboutandquote',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='aboutandquote',
            name='profileImage',
        ),
        migrations.RemoveField(
            model_name='aboutandquote',
            name='quoteContainerImage',
        ),
        migrations.RemoveField(
            model_name='aboutandquote',
            name='quotes',
        ),
        migrations.AddField(
            model_name='aboutandquote',
            name='class_completed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutandquote',
            name='client_taught',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutandquote',
            name='front_image',
            field=models.ImageField(null=True, upload_to='images/pics'),
        ),
        migrations.AddField(
            model_name='aboutandquote',
            name='grid_big',
            field=models.ImageField(null=True, upload_to='images/pics'),
        ),
        migrations.AddField(
            model_name='aboutandquote',
            name='grid_small_one',
            field=models.ImageField(null=True, upload_to='images/pics'),
        ),
        migrations.AddField(
            model_name='aboutandquote',
            name='grid_small_two',
            field=models.ImageField(null=True, upload_to='images/pics'),
        ),
        migrations.AddField(
            model_name='aboutandquote',
            name='instagram_follower',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutandquote',
            name='parrallex_img',
            field=models.ImageField(null=True, upload_to='images/pics'),
        ),
        migrations.AddField(
            model_name='aboutandquote',
            name='story',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutandquote',
            name='year_of_experiences',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
