# Generated by Django 5.1.7 on 2026-07-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0044_corevalues_rename_pinterest_aboutandquote_tiktok_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='phone_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='customservice',
            name='phone_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
