# Generated by Django 5.1.7 on 2026-07-28 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0046_alter_booking_phone_number_alter_customservice_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customservice',
            name='phone_number',
            field=models.CharField(blank=True, null=True),
        ),
    ]
