# Generated by Django 5.1.7 on 2026-07-28 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0047_alter_customservice_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customservice',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
